// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-pages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var PAGES = [
  { path: "/", title: "\u0391\u03C1\u03C7\u03B9\u03BA\u03AE", description: "Urban Response \u2014 \u03B5\u03BA\u03C0\u03B1\u03AF\u03B4\u03B5\u03C5\u03C3\u03B7 \u03C0\u03C1\u03BF\u03C3\u03C9\u03C0\u03B9\u03BA\u03AE\u03C2 \u03B1\u03C3\u03C6\u03AC\u03BB\u03B5\u03B9\u03B1\u03C2 \u03BA\u03B1\u03B9 \u03B5\u03C4\u03BF\u03B9\u03BC\u03CC\u03C4\u03B7\u03C4\u03B1\u03C2 \u03C3\u03C4\u03B7\u03BD \u03C0\u03CC\u03BB\u03B7." },
  { path: "/about", title: "\u03A3\u03C7\u03B5\u03C4\u03B9\u03BA\u03AC", description: "\u03A0\u03BF\u03B9\u03BF\u03B9 \u03B5\u03AF\u03BC\u03B1\u03C3\u03C4\u03B5 \u03BA\u03B1\u03B9 \u03C4\u03B9 \u03B5\u03AF\u03BD\u03B1\u03B9 \u03C4\u03BF Urban Response." },
  { path: "/mission", title: "\u0391\u03C0\u03BF\u03C3\u03C4\u03BF\u03BB\u03AE", description: "\u039F\u03B9 \u03C0\u03AD\u03BD\u03C4\u03B5 \u03B8\u03B5\u03BC\u03B5\u03BB\u03B9\u03CE\u03B4\u03B5\u03B9\u03C2 \u03B1\u03C1\u03C7\u03AD\u03C2 \u03C4\u03BF\u03C5 Urban Response." },
  { path: "/instructor", title: "\u0395\u03BA\u03C0\u03B1\u03B9\u03B4\u03B5\u03C5\u03C4\u03AE\u03C2", description: "\u03A3\u03C4\u03B1\u03CD\u03C1\u03BF\u03C2 \u039C\u03C0\u03B1\u03C1\u03BF\u03CD\u03C4\u03B1\u03C2 \u2014 Founder & Methodology Developer." },
  { path: "/training-tracks", title: "\u0395\u03BA\u03C0\u03B1\u03B9\u03B4\u03B5\u03C5\u03C4\u03B9\u03BA\u03AC \u0395\u03C0\u03AF\u03C0\u03B5\u03B4\u03B1", description: "\u03A4\u03B1 5 \u03C0\u03C1\u03BF\u03BF\u03B4\u03B5\u03C5\u03C4\u03B9\u03BA\u03AC \u03B5\u03C0\u03AF\u03C0\u03B5\u03B4\u03B1 \u03B5\u03BA\u03C0\u03B1\u03AF\u03B4\u03B5\u03C5\u03C3\u03B7\u03C2." },
  { path: "/faq", title: "\u03A3\u03C5\u03C7\u03BD\u03AD\u03C2 \u0395\u03C1\u03C9\u03C4\u03AE\u03C3\u03B5\u03B9\u03C2", description: "\u0391\u03C0\u03B1\u03BD\u03C4\u03AE\u03C3\u03B5\u03B9\u03C2 \u03C3\u03B5 \u03C3\u03C5\u03C7\u03BD\u03AD\u03C2 \u03B5\u03C1\u03C9\u03C4\u03AE\u03C3\u03B5\u03B9\u03C2 \u03B3\u03B9\u03B1 \u03C4\u03BF \u03C0\u03C1\u03CC\u03B3\u03C1\u03B1\u03BC\u03BC\u03B1." },
  { path: "/contact", title: "\u0395\u03C0\u03B9\u03BA\u03BF\u03B9\u03BD\u03C9\u03BD\u03AF\u03B1", description: "\u03A3\u03C4\u03BF\u03B9\u03C7\u03B5\u03AF\u03B1 \u03B5\u03C0\u03B9\u03BA\u03BF\u03B9\u03BD\u03C9\u03BD\u03AF\u03B1\u03C2 \u03BA\u03B1\u03B9 \u03C6\u03CC\u03C1\u03BC\u03B1." }
];
var list_pages_default = defineTool({
  name: "list_pages",
  title: "List site pages",
  description: "List every public page on the Urban Response site with its path, title, and a short description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(PAGES, null, 2) }],
    structuredContent: { pages: PAGES }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var CONTACT = {
  organization: "Urban Response",
  instructor: "\u03A3\u03C4\u03B1\u03CD\u03C1\u03BF\u03C2 \u039C\u03C0\u03B1\u03C1\u03BF\u03CD\u03C4\u03B1\u03C2",
  role: "Founder & Methodology Developer",
  location: "\u039A\u03B1\u03BB\u03B1\u03BC\u03B1\u03C1\u03B9\u03AC, \u0398\u03B5\u03C3\u03C3\u03B1\u03BB\u03BF\u03BD\u03AF\u03BA\u03B7",
  website: "https://urbanresponse.gr"
};
var get_contact_default = defineTool2({
  name: "get_contact",
  title: "Get contact info",
  description: "Return public contact information for Urban Response (instructor, location, website).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(CONTACT, null, 2) }],
    structuredContent: CONTACT
  })
});

// src/lib/mcp/tools/list-training-tracks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var TRACKS = [
  { level: 1, name: "Awareness", focus: "\u03A0\u03B1\u03C1\u03B1\u03C4\u03AE\u03C1\u03B7\u03C3\u03B7 \u03BA\u03B1\u03B9 situational awareness \u03C3\u03C4\u03B7\u03BD \u03BA\u03B1\u03B8\u03B7\u03BC\u03B5\u03C1\u03B9\u03BD\u03CC\u03C4\u03B7\u03C4\u03B1." },
  { level: 2, name: "Assessment", focus: "\u0395\u03BA\u03C4\u03AF\u03BC\u03B7\u03C3\u03B7 \u03BA\u03B1\u03C4\u03AC\u03C3\u03C4\u03B1\u03C3\u03B7\u03C2, OODA Loop, Cooper's Color Code." },
  { level: 3, name: "De-escalation", focus: "\u039B\u03B5\u03BA\u03C4\u03B9\u03BA\u03AE \u03B1\u03C0\u03BF\u03BA\u03BB\u03B9\u03BC\u03AC\u03BA\u03C9\u03C3\u03B7 \u03BA\u03B1\u03B9 \u03B4\u03B9\u03B1\u03C7\u03B5\u03AF\u03C1\u03B9\u03C3\u03B7 \u03AD\u03BD\u03C4\u03B1\u03C3\u03B7\u03C2." },
  { level: 4, name: "Decision", focus: "\u039B\u03AE\u03C8\u03B7 \u03B1\u03C0\u03CC\u03C6\u03B1\u03C3\u03B7\u03C2 \u03C5\u03C0\u03CC \u03C0\u03AF\u03B5\u03C3\u03B7 \u03C7\u03C9\u03C1\u03AF\u03C2 \u03C0\u03B1\u03BD\u03B9\u03BA\u03CC." },
  { level: 5, name: "Physical Response", focus: "\u0392\u03B1\u03C3\u03B9\u03BA\u03AE \u03C6\u03C5\u03C3\u03B9\u03BA\u03AE \u03B1\u03BD\u03C4\u03AF\u03B4\u03C1\u03B1\u03C3\u03B7 \u03B3\u03B9\u03B1 \u03B1\u03C5\u03C4\u03BF\u03C0\u03C1\u03BF\u03C3\u03C4\u03B1\u03C3\u03AF\u03B1." }
];
var list_training_tracks_default = defineTool3({
  name: "list_training_tracks",
  title: "List training tracks",
  description: "List the 5 progressive training levels of the Urban Response methodology.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TRACKS, null, 2) }],
    structuredContent: { tracks: TRACKS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "urban-response-mcp",
  title: "Urban Response",
  version: "0.1.0",
  instructions: "Public read-only tools for the Urban Response site. Use list_pages to discover pages, get_contact for contact info, and list_training_tracks for the 5 training levels.",
  tools: [list_pages_default, get_contact_default, list_training_tracks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
